### PR TITLE
Linux support v2 (resolve filepath)

### PR DESCRIPTION
**Pull request by LovelySanta**
For info about the issue: https://github.com/TheCherno/Hazel/pull/82#issuecomment-523330305
###### Explained by taking windows example:
1. When creating a new application, it will resolve its location in `Application::Application`:
https://github.com/LovelySanta/Hazel/blob/5a69d42dcd50d99945917771aac02bfacee8411e/Hazel/src/Hazel/Application.cpp#L22-L23
https://github.com/LovelySanta/Hazel/blob/5a69d42dcd50d99945917771aac02bfacee8411e/Hazel/src/Hazel/Application.cpp#L81-L102
2. When creating a texture, it will resolve its filepath when calling the abstracted implementation (here OpenGlTextrue2D)
https://github.com/LovelySanta/Hazel/blob/5a69d42dcd50d99945917771aac02bfacee8411e/Hazel/src/Hazel/Renderer/Texture.cpp#L16
https://github.com/LovelySanta/Hazel/blob/5a69d42dcd50d99945917771aac02bfacee8411e/Hazel/src/Hazel/Application.cpp#L112-L119
3. Post build command to copy assets to bin location (relative to the exe as where it is in distrbution)
https://github.com/LovelySanta/Hazel/blob/5a69d42dcd50d99945917771aac02bfacee8411e/premake5.lua#L186-L192

###### To do before this can be merged
- [ ] Resolve `Application::CreateAbsoluteDirectoryPath()`
    - [X] Windows
    - [ ] Linux
- [ ] Resolve `Application::ResolvePath(const std::string& path)`
    - [X] Windows
    - [ ] Linux  *This might work cross platform, but needs testing*
- [ ] Post build command to copy assets folder
    - [X] Windows
    - [ ] Linux

### CODE REVIEW

**Comment by LovelySanta** [comment]
For linux:  the long (2nd post) on this page seems promissing: https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe

**Comment by LovelySanta** [comment]
Initial implementation of linux version of the path methode, still need premake postbuild commnad

also still need to check if I have to add a `/` at the end of the path and if it is working... didn't check it off yet in the todo list for this reason. The windows version is tested and working.

**Comment by DaveAxiom** [comment]
There's a lot of code in this patch!

I see that this patch is saving a full path. There are a few lessons to be learned. Usually implementing the most simple solution is the best. A relative path would work well. The program can check if the file asset is in the proper sub directory. Then it can fall back on looking two parent directories up using a relative path for the asset directory. Premake in this case would pass directory structure information to the Makefiles for the debug build.

Learning a lesson from Napster many years ago. Napster used full paths in its internals but hid them only from the user. Since that client shared files, it broadcast full file paths to everyone looking on the system. Napster peers would use that full path to request a file download! It was an unnecessary security hazard!

Linux systems running Hazel using full paths would fail to read files if the working directory was moved. Windows locks running program files which would prevent this failure but being a software developer that's debugging, moving the running program with its assets is a possibility. Maybe someone might want to continue running a program after it was moved into the trash!

**Comment by LovelySanta** [comment]
> The program can check if the file asset is in the proper sub directory. Then it can fall back on looking two parent directories up using a relative path for the asset directory. Premake in this case would pass directory structure information to the Makefiles for the debug build.

I'm looking at a bigger picture, assume we develop our app in `C:/dev/Hazel`, in debug mode this is fine, it has a relative path to where it was developed, and in that case going 2 directories up, searching for the assets folder is within reason.

Now let's assume we're in distributing mode, to keep it simple, we got a version distributed by steam, it is in `C:/Program Files (x86)/Steam/steamapps/common/GameNameThatUsesHazel`, here the compiled program will also look for a relative path as in the section above, where going 2 directories up to search for the assets folder (still searching somewhere in `C:/dev/Hazel`) will have no succes (as the directory doesn't exist most likely). This is why - for assets at least - I was thinking about keeping an absolute path, since assets are downloaded together with the compiled binaries...

Ofcourse I'm still open to other suggestions for ways to not require a full file path in these cases... However, as I don't know any as of this point, the part below in this post will assume we still require the full file path..

> Learning a lesson from Napster many years ago. Napster used full paths in its internals but hid them only from the user. Since that client shared files, it broadcast full file paths to everyone looking on the system. Napster peers would use that full path to request a file download! It was an unnecessary security hazard!

Requesting a file from someone could still broadcast the relative path and only resolve that internaly on the requested pc. As of know I am resolving the file path in the abstracted class before passing it into the OpenGL implementation:
https://github.com/LovelySanta/Hazel/blob/c8cc709bf2a7e7e3d772e8eeb42148a8e55cdcfe/Hazel/src/Hazel/Renderer/Texture.cpp#L16
Reading what you've said before about Napster, what if we move this to the point where we actualy use the path last minute?
https://github.com/LovelySanta/Hazel/blob/c8cc709bf2a7e7e3d772e8eeb42148a8e55cdcfe/Hazel/src/Platform/OpenGL/OpenGLTexture.cpp#L15
This way, we're always using a relative path in the code, but when actualy looking localy, we use the absolute path.

> Linux systems running Hazel using full paths would fail to read files if the working directory was moved. Windows locks running program files which would prevent this failure but being a software developer that's debugging, moving the running program with its assets is a possibility. Maybe someone might want to continue running a program after it was moved into the trash!

The only thing I can think of working after moving, the relative file path doesn't work as explained before, is trying to resolve the abolute file path again. At that point using `argv[0]` is useless and so $PATH becomes as well. A solid fallback methode would be needed, where we can set argv[0] to nullptr and directly use the fallback methode..., and when resolving a file path, actualy try and see if that file exist, if not, try to relocate the absolute file path, and try again.

**Comment by DaveAxiom** [comment]
Relative paths can be used in all cases from what I'm seeing. In all builds, Hazel looks in `./assets/textures/`. If `Checkerboard.png` isn't found under the working directory, the debug build will additionally check in `../../Sandbox/assets/textures/`. That relative directory path would be from the working directory of `./bin/Debug-linux-x86_64` on Linux or similarly `./bin/Debug-windows-win64` on Windows.

**Comment by LovelySanta** [comment]
Ok, so then we only have to move the assets folder into the bin directory to solve this? Instead of resolving an absolute path.
We might even use [command tokens](https://github.com/premake/premake-core/wiki/Tokens#command-tokens) so we can use have cross platform post build commands

EDIT: implemented in #16

**Comment by LovelySanta** [comment]
@DaveAxiom, shouldn't we move on to https://github.com/LovelySanta/Hazel/pull/16 instead of using the absolute path?

**Comment by DaveAxiom** [comment]
@LovelySanta I'm taking this patch as a basis for a new simplified patch that uses only relative paths. #16 copies asset files around which is too quirky for me.

**Comment by LovelySanta** [comment]
> @LovelySanta I'm taking this patch as a basis for a new simplified patch that uses only relative paths. #16 copies asset files around which is too quirky for me.

Great! I can live with that!

**Pull request closed without merging**
